# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknGraph < Formula
  desc "Tekton CLI - The command line interface for Pipeline, PipelineRun presentation in Graph"
  homepage "https://github.com/sergk/tkn-graph"
  version "0.6.3"
  license "Apache-2.0"

  depends_on "git"
  depends_on "tektoncd-cli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.3/tkn-graph_0.6.3_Darwin_x86_64.tar.gz"
      sha256 "aac00381d124ff73e00ce7afd47f1a4311bfcf607d1abe7113323f3422536b9d"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.3/tkn-graph_0.6.3_Darwin_aarch64.tar.gz"
      sha256 "ac16e307e22f483403760d72e5f5090eb5ba444bdd337d291af5cf3160a25a95"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.3/tkn-graph_0.6.3_Linux_x86_64.tar.gz"
        sha256 "f40ba66f97742baf2c22bcc926f3e0343aa09ff342e556322c88b0a6df732116"

        def install
          bin.install_symlink "tkn" => "kubectl-tkn-graph"
          bin.install "tkn-graph" => "tkn-graph"
          output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
          (bash_completion/"tkn-graph").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
          (zsh_completion/"_tkn-graph").write output
          prefix.install_metafiles
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.3/tkn-graph_0.6.3_Linux_aarch64.tar.gz"
        sha256 "609dee18686c25d3b4269c4ad022cca8f5ef6f4b4cb81b745be94233bacc94b7"

        def install
          bin.install_symlink "tkn" => "kubectl-tkn-graph"
          bin.install "tkn-graph" => "tkn-graph"
          output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
          (bash_completion/"tkn-graph").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
          (zsh_completion/"_tkn-graph").write output
          prefix.install_metafiles
        end
      end
    end
  end

  test do
    system "#{bin}/tkn-graph", "--help"
  end
end
