# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknGraph < Formula
  desc "Tekton CLI - The command line interface for Pipeline, PipelineRun presentation in Graph"
  homepage "https://github.com/sergk/tkn-graph"
  version "0.7.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "tektoncd-cli" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.7.0/tkn-graph_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "ad56ded64c0ee0570e63f4b19d92de9cb5578c036f3fefc1eaf784b012327b22"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.7.0/tkn-graph_0.7.0_Darwin_aarch64.tar.gz"
      sha256 "b650801b2b695dfc7cff118f8905fd3225761a63d99875ac3cc73016b499aa1c"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sergk/tkn-graph/releases/download/v0.7.0/tkn-graph_0.7.0_Linux_x86_64.tar.gz"
        sha256 "2351842a1d036ac4cc2ec0d0a062aef3570a8fdb07ed20374bdc4517b8c042d7"

        def install
          bin.install_symlink "tkn" => "kubectl-tkn-graph"
          bin.install "tkn-graph" => "tkn-graph"
          output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
          (bash_completion/"tkn-graph").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
          (zsh_completion/"_tkn-graph").write output
          prefix.install_metafiles
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sergk/tkn-graph/releases/download/v0.7.0/tkn-graph_0.7.0_Linux_aarch64.tar.gz"
        sha256 "8fd889ec7ecec302a7df23a0ddc71766c60bb6085b997b13484a09155e14c254"

        def install
          bin.install_symlink "tkn" => "kubectl-tkn-graph"
          bin.install "tkn-graph" => "tkn-graph"
          output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
          (bash_completion/"tkn-graph").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
          (zsh_completion/"_tkn-graph").write output
          prefix.install_metafiles
        end
      end
    end
  end

  test do
    system "#{bin}/tkn-graph", "--help"
  end
end
