# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknGraph < Formula
  desc "Tekton CLI - The command line interface for Pipeline, PipelineRun presentation in Graph"
  homepage "https://github.com/sergk/tkn-graph"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.2/tkn-graph_0.6.2_Darwin_aarch64.tar.gz"
      sha256 "f4351c268ba49687d15b5dbfb2ffa935b636fcf950ddc740581c3b317a097c2b"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.2/tkn-graph_0.6.2_Darwin_x86_64.tar.gz"
      sha256 "c92d10deb03c90fa27d03a64da806239bb3651b3a25cf7b475d8b85952f68c6c"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.2/tkn-graph_0.6.2_Linux_aarch64.tar.gz"
      sha256 "c68d8b9cdac0bca2101bdc7ba32095049d9bfecc9e65b2b517cd26c83999c58b"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.2/tkn-graph_0.6.2_Linux_x86_64.tar.gz"
      sha256 "2153e0e24724a86bf19c744efe78ed54912774caee285d504e9a40af0c5e86ee"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/tkn-graph", "--help"
  end
end
