# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknGraph < Formula
  desc "Tekton CLI - The command line interface for Pipeline, PipelineRun presentation in Graph"
  homepage "https://github.com/sergk/tkn-graph"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.5.0/tkn-graph_0.5.0_Darwin_aarch64.tar.gz"
      sha256 "2b5fff3c07ab9936033e01b611227c4096b720c7774f0a38394bacf297cbb06b"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.5.0/tkn-graph_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "6776c74c62d8a65cecd12e40e975779e23fb147a68262bf9a5ef61ddbf42e79b"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.5.0/tkn-graph_0.5.0_Linux_aarch64.tar.gz"
      sha256 "50fa5d0292e41e273addb8c6052f7979ba86bbdc4eb9dfe3b9beabe8bb6ef318"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.5.0/tkn-graph_0.5.0_Linux_x86_64.tar.gz"
      sha256 "58cf52832b52d143188fe4ca7af48de7e3fa96bc21ca449cd2346bf04cea848e"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/tkn-graph", "--help"
  end
end
