# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknGraph < Formula
  desc "Tekton CLI - The command line interface for Pipeline, PipelineRun presentation in Graph"
  homepage "https://github.com/sergk/tkn-graph"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.0/tkn-graph_0.6.0_Darwin_aarch64.tar.gz"
      sha256 "c0291e200f00af6322499fb3e74f088a0b4d2e5b1945dc03f995d0ca5bc61e43"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.0/tkn-graph_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "62e9ba7de10bcbda5befc30bc9408a5d071cd2ae573560f35247edff5e94913a"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.0/tkn-graph_0.6.0_Linux_aarch64.tar.gz"
      sha256 "ada936344d0b7597e76b8e7c8842eba423d3793ab2b4f6e83513104c1938bfc3"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Sergk/tkn-graph/releases/download/v0.6.0/tkn-graph_0.6.0_Linux_x86_64.tar.gz"
      sha256 "2f3ae4311000ef79eb14c277176ce97f754dd0e6069b58766bc56cf19694d3ac"

      def install
        bin.install_symlink "tkn" => "kubectl-tkn-graph"
        bin.install "tkn-graph" => "tkn-graph"
        output = Utils.popen_read("SHELL=bash #{bin}/tkn-graph completion bash")
        (bash_completion/"tkn-graph").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/tkn-graph completion zsh")
        (zsh_completion/"_tkn-graph").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/tkn-graph", "--help"
  end
end
